[theme]
base = "light"
primaryColor = "#0e9d6c"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f8f6"
textColor = "#12161a"
font = "sans serif"

[server]
headless = false
runOnSave = true

[browser]
gatherUsageStats = false
